### ISSUE TITLE
Displaying emojis on Windows

### ISSUE THREAD

**Issue by loreabad6** [luukvdmeer/loRe#2]
Hi 🐻! 
I am sad because I cannot see emojis on the very beautiful messages I get on my `loRe` package. I discovered that if the content of `message()` is wrapped around `cat()` things work. At least on my local test. Can you please please add 🐱 to my package? 

🐰

**Comment by luukvdmeer** [comment]
Can you check if it works? :bear:

**Comment by loreabad6** [comment]
Thank you!!! 👯
